# Generated by Django 4.0.6 on 2022-08-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inicio',
            old_name='contenidoi',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='contenidop',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagenp',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombrep',
            new_name='nombre',
        ),
    ]
