# Generated by Django 4.0.6 on 2022-08-02 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_contenidoi_inicio_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='media/blog'),
        ),
    ]
