# Generated by Django 4.1.1 on 2022-10-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cita_medica',
            new_name='Cita',
        ),
        migrations.RenameModel(
            old_name='Cita_medica_tratamiento',
            new_name='Tratamiento',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='apellidosd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='direcciond',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nombresd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='estado',
            field=models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='estado',
            field=models.CharField(choices=[('on', 'Activo'), ('off', 'Inactivo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
    ]
