/*Consultas Avanzadas*/
select * 
from actor
where first_name = "penelope";

SELECT *
FROM actor
WHERE FIRST_NAME LIKE "PENELOPE";

/*nombre que empiece con p*/
SELECT *
FROM actor
WHERE FIRST_NAME LIKE "P%";

/*nombre que termine con p*/
SELECT *
FROM actor
WHERE FIRST_NAME LIKE "%P";

/*nombre que contenga la p*/
SELECT *
FROM actor
WHERE FIRST_NAME LIKE "%P%";

/*apellido que empiece con la b*/
SELECT *
FROM actor
WHERE LAST_NAME LIKE "B%";

/* Group by - Operador de agrupacion
AGRUPAR POR APELLIDO Y CONTAR LA CANTIDAD DE ACTORES CON EL MISMO APELLIDO*/
SELECT LAST_NAME AS APELLIDO,COUNT(LAST_NAME) AS CANTIDAD_ACTORES
FROM actor
GROUP BY LAST_NAME;

/* AS RENOMBRA LA COLUMNA (ALIAS) 
CANTIDAD ACTORES CON APELLIDO QUE EMPIECE CON LA C*/
SELECT COUNT(LAST_NAME) AS CANTIDAD_APELLIDOS_EMPIEZAN_C
FROM actor
WHERE LAST_NAME LIKE "C%";

/*ORDER BY - OPERADOR DE ORDEN
ASC - ORDEN ASCENDENTE - A la Z
DESC - ORDEN DESCENTE - Z la A 
ORDENAR POR APELLIDO*/
SELECT *
FROM actor
ORDER BY LAST_NAME DESC;